Splt 8 create routes for login
koushikgg2001/Split pull request #3
Opened 2024-12-28 14:49 UTC by VarshiniBS

2024-12-29 04:42 UTC, koushikgg2001 commented
Also please add description at the top

2024-12-31 15:07 UTC, koushikgg2001 requested changes

2024-12-31 15:07 UTC, koushikgg2001 commented on server/controllers/userController.js
> +    }
"else" keyword can be removed if return statement is present inside "if" condition

2024-12-31 15:07 UTC, koushikgg2001 commented on server/controllers/userController.js
> +    const loginpassword = req.body.password;
use camelCase(also for other occurrences)

2024-12-31 15:07 UTC, koushikgg2001 commented on .gitignore
> +server/.env
you can remove end of line symbol using new line at the end of file

2024-12-31 15:07 UTC, koushikgg2001 commented on server/routes/userRoutes.js
>  const router = express.Router();
usage of express.json() is also needed here, otherwise req.body will always be undefined in controller

2024-12-31 15:07 UTC, koushikgg2001 commented on server/controllers/userController.js
> +      const password = req.body.password;
single statement is preferred here(also for other occurrences)

2024-12-31 15:07 UTC, koushikgg2001 commented on server/controllers/userController.js
> +  }catch(err)
formatting

2024-12-31 15:07 UTC, koushikgg2001 commented on server/controllers/userController.js
>  const getAllUsers = (req, res) => {
modify the function

2024-12-31 15:07 UTC, koushikgg2001 commented on server/controllers/userController.js
>    const userId = req.params.id;
modify the function to get all details of user

2025-01-01 16:00 UTC, koushikgg2001 commented on server/controllers/userController.js
> +        res.send("Email already exists. Try logging in.");
send json instead of string similar to line 31 and 36

2025-01-02 14:17 UTC, VarshiniBS commented on server/routes/userRoutes.js
>  const router = express.Router();
I added body-parser in server.js hence not giving an error
![image](https://github.com/user-attachments/assets/c4139ea7-e927-4121-b5ac-928d6a558022)

2025-01-02 14:17 UTC, VarshiniBS commented on server/routes/userRoutes.js
>  const router = express.Router();
Does it need to be express.json only?

2025-01-02 14:18 UTC, VarshiniBS commented on .gitignore
> +server/.env
is that necessary?

2025-01-02 14:20 UTC, VarshiniBS commented on server/controllers/userController.js
>  const getAllUsers = (req, res) => {
I am still not sure what is the use of this function and do we really need it, hence not defined properly

2025-01-02 14:21 UTC, VarshiniBS commented on server/controllers/userController.js
> +  }catch(err)
done

2025-01-02 14:21 UTC, VarshiniBS commented on server/controllers/userController.js
> +    }
done

2025-01-02 14:21 UTC, VarshiniBS commented on server/controllers/userController.js
> +    const loginpassword = req.body.password;
done

2025-01-02 14:21 UTC, VarshiniBS commented on server/controllers/userController.js
> +        res.send("Email already exists. Try logging in.");
done

2025-01-02 14:21 UTC, koushikgg2001 commented on .gitignore
> +server/.env
As a convention, we do. You can skip if not necessary

2025-01-02 14:39 UTC, koushikgg2001 commented on server/routes/userRoutes.js
>  const router = express.Router();
Any middleware can be used but it is necessary

2025-01-02 14:47 UTC, koushikgg2001 commented on server/controllers/userController.js
>  const getAllUsers = (req, res) => {
Then you can remove the function for now

2025-01-05 10:24 UTC, koushikgg2001 commented on server/routes/userRoutes.js
>  const router = express.Router();
You can use router.use(bodyParser.json()); since we pass json from frontend

2025-01-05 11:10 UTC, koushikgg2001 commented on server/controllers/userController.js
> +      return res.status(200).json({ message: "Email already exists. Please try logging in" });
use 409

2025-01-12 13:51 UTC, merged